// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesMonitor.Data;

#nullable disable

namespace SalesMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesMonitor.Models.ClientActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID продукта_");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageOrderInterval")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Средний интервал между заказами");

                    b.Property<DateTime?>("LastSaleDate")
                        .HasColumnType("date")
                        .HasColumnName("Дата последней продажи");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ID продукта");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Активность клиентов");
                });

            modelBuilder.Entity("SalesMonitor.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID продукта");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Себестоимость");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("date")
                        .HasColumnName("Дата добавления в ассортимент");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean")
                        .HasColumnName("В продаже");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("Название продукта");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Цена продажи");

                    b.HasKey("Id");

                    b.ToTable("Продукты");
                });

            modelBuilder.Entity("SalesMonitor.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID продажи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Margin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Маржа");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ID продукта");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Количество");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("date")
                        .HasColumnName("Дата продажи");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Общая сумма чека");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Продажи");
                });

            modelBuilder.Entity("SalesMonitor.Models.ClientActivity", b =>
                {
                    b.HasOne("SalesMonitor.Models.Product", "Product")
                        .WithOne("ClientActivity")
                        .HasForeignKey("SalesMonitor.Models.ClientActivity", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesMonitor.Models.Sale", b =>
                {
                    b.HasOne("SalesMonitor.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesMonitor.Models.Product", b =>
                {
                    b.Navigation("ClientActivity");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
